import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import StyledComponentsRegistry from "../lib/AntdRegistry";

import Header from "./template/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <StyledComponentsRegistry>
          {children}
          <Analytics />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
